spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/longs?serverTimezone=UTC&useSSL=false
    username: root
    password: 1234

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  servlet:
    multipart:
      file-size-threshold: 1MB
      location: C:/Temp
      max-file-size: 100MB
      max-request-size: 100MB

  sql:
    init:
      data-locations: classpath:data.sql
      schema-locations: classpath:schema.sql
      mode: always

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    s3:
      bucket: act-longs
    region:
      static: ap-northeast-2
    stack:
      auto: false

logging:
  level:
    root: debug
    org:
      hibernate:
        SQL: debug
        type: trace

ffmpeg:
  path: ${FFMPEG_PATH}
ffprobe:
  path: ${FFPROBE_PATH}
