name: '[PR]도커 E2E 테스트'

on:
  push:
    branches:
      - chore/SL-133

jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: "11"

      - name: BE application var injection[local]
        uses: microsoft/variable-substitution@v1
        with:
          files: '/home/runner/work/longs-backend/longs-backend/src/main/resources/application-local.yml'
        env:
          cloud.aws.credentials.access-key: ${{secrets.AWS_ACCESS_KEY}}
          cloud.aws.credentials.secret-key: ${{secrets.AWS_SECRET_KEY}}
      
      - name: BE application var injection[dev]
        uses: microsoft/variable-substitution@v1
        with:
          files: '/home/runner/work/longs-backend/longs-backend/src/main/resources/application-dev.yml'
        env:
          cloud.aws.credentials.access-key: ${{secrets.AWS_ACCESS_KEY}}
          cloud.aws.credentials.secret-key: ${{secrets.AWS_SECRET_KEY}}

      - name: set +x
        run: chmod +x ./gradlew

      - name: Gradle editorconfigFormat
        run: ./gradlew editorconfigFormat

      - name: Build with Gradle
        run: ./gradlew build --exclude-task test

      - name: Build Docker image
        run: docker build vidigummy/longs-svr:${{ github.run_id }} .

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: docker push vidigummy/longs-svr:${{ github.run_id }} 
  deploy:
    needs: build-and-push-docker
    runs-on: ubuntu-latest
    steps:
      - name: excute docker compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEV_GCE_HOST }}
          username: ${{ secrets.GCE_USERNAME }}
          key: ${{ secrets.GCE_SSH_KEY }}
          password: ${{ secrets.GCE_ROOT_PW }}
          port: 22
          script: |
            cd /app/longs-env/env-dev
            docker compose up -d
