name: '[PR]도커 E2E 테스트'

on:
  push:
    branches:
      - NO-ISSUE/E2ETEST

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: "11"

      - name: BE application var injection[local]
        uses: microsoft/variable-substitution@v1
        with:
          files: '/home/runner/work/longs-backend/longs-backend/src/main/resources/application-local.yml'
        env:
          cloud.aws.credentials.access-key: ${{secrets.AWS_ACCESS_KEY}}
          cloud.aws.credentials.secret-key: ${{secrets.AWS_SECRET_KEY}}
      
      - name: BE application var injection[dev]
        uses: microsoft/variable-substitution@v1
        with:
          files: '/home/runner/work/longs-backend/longs-backend/src/main/resources/application-dev.yml'
        env:
          cloud.aws.credentials.access-key: ${{secrets.AWS_ACCESS_KEY}}
          cloud.aws.credentials.secret-key: ${{secrets.AWS_SECRET_KEY}}

      - name: set +x
        run: chmod +x ./gradlew

      - name: Gradle editorconfigFormat
        run: ./gradlew editorconfigFormat

      - name: Build with Gradle
        run: ./gradlew build --exclude-task test

      - name: Build Docker image
        run: docker build -t vidigummy/longs-svr .

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: docker push vidigummy/longs-svr
