name: '[MASTER]배포'

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: "11"

      - name: set +x
        run: chmod +x ./gradlew

      - name: Gradle editorconfigFormat
        run: ./gradlew editorconfigFormat

      - name: Build with Gradle
        run: ./gradlew clean build --exclude-task test

      - name: Build Docker image
        run: docker build --no-cache -t vidigummy/longs-svr-pub:${{ github.run_id }} -t vidigummy/longs-svr-pub:latest -f pub.Dockerfile .

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: docker push vidigummy/longs-svr-pub:${{ github.run_id }}

      - name: Push Docker latest
        run: docker push vidigummy/longs-svr-pub:latest
  
  deploy:
    needs: build-and-deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v2

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.AWS_SVR_SECRET_KEY }}
      
      - name: Connect to remote server and run command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_VM_BS_HOST }}
          username: ${{ secrets.AWS_VM_USERNAME }}
          key: ${{ secrets.AWS_SVR_SECRET_KEY }}
          port: 22
          command: |
            cd /home/ubuntu/.ssh
            result=$(./loginToMaster.sh)
            echo "$result"
