name: '[DEV] RESTART DEV SVR'

on:
  push:
    branches:
      - chore/SL-133
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: excute docker compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEV_GCE_HOST }}
          username: ${{ secrets.GCE_USERNAME }}
          key: ${{ secrets.GCE_SSH_KEY }}
          port: 22
          script: |
            cd /app/longs-env/env-dev
            docker compose up -d